# Configuration MTG API
mtg:
  api:
    base-url: https://api.magicthegathering.io/v1
  images:
    storage-path: ./data/images  # Dossier local pour stocker les images
    base-url: /api/images        # URL de base pour servir les images
    download-enabled: true       # Activer le téléchargement automatique
    max-download-threads: 5      # Nombre de threads pour télécharger en parallèle

# Configuration des logs
logging:
  level:
    com.pcagrad.magic: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Profils pour différents environnements
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com.pcagrad.magic: DEBUG
    org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://your-prod-server:3306/mtg_cards?useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME:mtg_user}
    password: ${DB_PASSWORD:mtg_password}
  jpa:
    hibernate:
      ddl-auto: validate  # En production, ne pas créer les tables automatiquement
mtg:
  images:
    storage-path: /var/data/mtg-images
logging:
  level:
    com.pcagrad.magic: WARN